[UPP.BU3pv]
2 = "1350" #"Диаметр бандажа первой колёсной пары" // (мм)"
3 = "1350" #"Диаметр бандажа второй колёсной пары" // (мм)"
4 = "1" #"Наличие МПМЭ"
5 = "111" #"Тип локомотива или электросекции"
6 = "1" #"Номер локомотива или электросекции"
7 = "42" #"Число зубьев датчика угла поворота"
8 = "100" #"Верхний предел шкалы"
9 = "100" #"Дискретность регистрации пути" //"Масштаб регистрации шкалы для БР-2М"
10 = "1.0" #"Дискретность регистрации скорости" //"Дискретность регистрации скорости для БР-2М"
11 = "0" #"Наличие БР-2М"
12 = "16" #"Верхний предел измерения давления в ТЦ" // по 2 каналу"
13 = "1" #"Признак наличия блока контроля"
14 = "45" #"Уставка скорости V(ж)"
15 = "30" #"Уставка скорости V(кж)"
16 = "10" #"Уставка скорости V(упр)"
17 = "1" #"Признак одной или двух кабин или МВПС"
18 = "10" #"Код варианта системы АЛС"
19 = "0" #"Признак наличия БУС"
20 = "15" #"Кол-во метров для гребнесмазки"
21 = "0" #"Наличие комплекса КВАРТА"
22 = "10" #"Дискретность регистрации топлива"
25 = "0" #"Количество дополнительных параметров"
26 = "4" #"Количество знаков табельного номера"